# Services planning

In [1]:
import pandas as pd
import geopandas as gpd


blocks = pd.read_pickle('C:/itmo/MASTER_PLAN/blocksnet/examples/data/model_upd.pickle')
blocks.head(3)

,geometry,residential,business,recreation,industrial,transport,special,agriculture,land_use,share,...,capacity_prison,count_prison,capacity_landfill,count_landfill,capacity_plant_nursery,count_plant_nursery,capacity_greenhouse_complex,count_greenhouse_complex,capacity_warehouse,count_warehouse
0,"POLYGON ((349424.859 6631180.891, 349424.751 6...",0.000,0.0,0.000000,0.0,1.000000,0.0,0.000000,LandUse.TRANSPORT,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,"POLYGON ((352083.617 6633950.146, 352240.448 6...",0.099,0.0,0.079912,0.0,0.401072,0.0,0.417018,LandUse.AGRICULTURE,0.417018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,"POLYGON ((346700.642 6618453.176, 346681.107 6...",1.000,0.0,0.000000,0.0,0.000000,0.0,0.000000,LandUse.RESIDENTIAL,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
accessibility_matrix = pd.read_pickle('../../data/acc_mx.pickle')
accessibility_matrix.head()

c:\itmo\MASTER_PLAN\blocksnet\.venv\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,0,1,2,3,4,5,6,7,8,9,...,9358,9359,9360,9361,9362,9363,9364,9365,9366,9367
0,0.0000,58.15625,74.187500,76.937500,66.8125,80.5000,92.18750,66.56250,65.68750,106.8750,...,70.0000,72.1875,72.0000,73.3125,73.2500,74.0000,75.5000,83.1875,75.0000,73.2500
1,56.2500,0.00000,99.687500,102.375000,88.1250,76.1250,113.43750,89.43750,88.56250,96.3125,...,65.6250,67.7500,67.6875,69.0000,68.8750,69.6875,71.1875,78.8125,70.6875,68.8750
2,74.5000,96.50000,0.000000,5.347656,74.0000,118.8125,92.06250,64.43750,63.56250,134.5000,...,108.3125,110.4375,110.3750,111.6875,111.5625,112.3750,113.8125,121.5000,113.3750,111.5625
3,77.2500,99.25000,5.347656,0.000000,76.7500,121.5625,90.12500,67.18750,66.31250,137.2500,...,111.0625,113.1875,113.0625,114.3750,114.3125,115.0625,116.5625,124.2500,116.1250,114.3125
4,70.1875,90.56250,82.375000,85.125000,0.0000,110.5000,35.53125,45.15625,44.28125,89.8750,...,100.0000,102.1250,102.0000,103.3125,103.2500,104.0000,105.5000,113.1875,105.0000,103.2500

### Service distribution

In [3]:
basic_services = {
    "kindergarten": 0.5,
    "school": 0.5,
    "pharmacy": 0.2,
    "polyclinics": 0.3,
    "convenience": 0.2,   
    "cafe": 0.15,
    "playground": 0.2,
    "post": 0.1,
    "hairdresser": 0.1,
    "park": 0.3,
    "parking":0.1
}
advanced_services = {
    "hospital": 0.5,
    "supermarket": 0.4,
    "restaurant": 0.2,
    "bank": 0.3,
    "fuel": 0.25,
    "police": 0.2,
    "cinema": 0.2,
    "market": 0.2,
    "religion": 0.5,
    "multifunctional_center": 0.1,
    "train_building": 0.1,
    "cemetery": 0.1,
    "notary": 0.1,
    "pitch": 0.2,
    "houseware":0.1
}
comfort_services = {
    "mall": 0.3,
    "swimming_pool": 0.4,
    "theatre": 0.2,
    "museum": 0.2,
    "university": 0.2,
    "sanatorium": 0.2,
    "zoo": 0.1,
    "reserve": 0.1,
    "animal_shelter": 0.1,
    "aeroway_terminal": 0.2,
    "landfill": 0.1,
    "bar": 0.3,
    "hotel": 0.3,
    "dog_park": 0.2
}


def get_service_weight(service_name):
    if service_name in basic_services:
        return 0.5714 * basic_services[service_name]
    elif service_name in advanced_services:
        return 0.2857 * advanced_services[service_name]
    elif service_name in comfort_services:
        return 0.1429 * comfort_services[service_name]
    return 0

### Service types and weights

In [4]:
chosen_service_types = set(basic_services) | set(advanced_services) | set(comfort_services)
service_weights = {service_type: get_service_weight(service_type) for service_type in chosen_service_types if f'capacity_{service_type}' in blocks.columns}

### Select ID of optimized blocks

In [ ]:
from blocksnet.enums import LandUse

blocks_lu = {
    i:LandUse.RESIDENTIAL for i in blocks[blocks.is_project].index
}

### Initialize and run optimizer

In [ ]:
from blocksnet.optimization.services import (
    TPEOptimizer,
    WeightedObjective,
    WeightedConstraints,
    Facade,
    GradientChooser,
    RandomOrder,
    AreaSolution
)

MAX_TIME_SEC = 60*10
MAX_PROV_EVALS = 100
MAX_OPT_RUNS = 1000

c:\itmo\MASTER_PLAN\blocksnet\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
blocks.head(4)

,geometry,residential,business,recreation,industrial,transport,special,agriculture,land_use,share,...,capacity_prison,count_prison,capacity_landfill,count_landfill,capacity_plant_nursery,count_plant_nursery,capacity_greenhouse_complex,count_greenhouse_complex,capacity_warehouse,count_warehouse
0,"POLYGON ((349424.859 6631180.891, 349424.751 6...",0.000000,0.0,0.000000,0.0,1.000000,0.0,0.000000,LandUse.TRANSPORT,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,"POLYGON ((352083.617 6633950.146, 352240.448 6...",0.099000,0.0,0.079912,0.0,0.401072,0.0,0.417018,LandUse.AGRICULTURE,0.417018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,"POLYGON ((346700.642 6618453.176, 346681.107 6...",1.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,LandUse.RESIDENTIAL,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,"POLYGON ((347043.363 6618261.219, 347042.608 6...",0.729125,0.0,0.270875,0.0,0.000000,0.0,0.000000,LandUse.RESIDENTIAL,0.729125,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
blocks.site_area = blocks.to_crs(blocks.estimate_utm_crs()).area

In [9]:
var_adapter = AreaSolution(blocks_lu)

facade = Facade(
    blocks_lu=blocks_lu,
    blocks_df=blocks,
    accessibility_matrix=accessibility_matrix,
    var_adapter=var_adapter,
)

from tqdm import tqdm

for service_type, weight in tqdm(service_weights.items()):
    facade.add_service_type(service_type, weight, blocks.rename(columns={f'capacity_{service_type}': 'capacity'})[['capacity']].fillna(0))

objective = WeightedObjective(num_params=facade.num_params, facade=facade, weights=service_weights, max_evals=MAX_PROV_EVALS)

constraints = WeightedConstraints(num_params=facade.num_params, facade=facade, priority=service_weights)

100%|██████████| 36/36 [21:22<00:00, 35.62s/it]

In [10]:
tpe_optimizer = TPEOptimizer(
    objective=objective, constraints=constraints, vars_order=RandomOrder(), vars_chooser=GradientChooser(facade, num_params=facade.num_params, num_top=5)
)

best_x, best_val, perc, func_evals = tpe_optimizer.run(max_runs=MAX_OPT_RUNS, timeout=MAX_TIME_SEC, initial_runs_num=1)

[I 2025-10-17 16:16:25,759] A new study created in memory with name: no-name-37260994-5b72-49f5-ab26-e78a2849742c
Best trial: 0. Best value: 2.21936:   0%|          | 1/1000 [00:13<3:38:38, 13.13s/it, 13.13/300 seconds]

[I 2025-10-17 16:16:38,902] Trial 0 finished with value: 2.2193561511084323 and parameters: {'x_13': 60, 'x_10': 18500, 'x_14': 50, 'x_26': 400, 'x_18': 0, 'x_15': 1250, 'x_12': 20000, 'x_20': 270, 'x_4': 11000, 'x_24': 10000, 'x_11': 0, 'x_5': 24000, 'x_23': 0, 'x_21': 0, 'x_0': 150, 'x_25': 0, 'x_19': 700, 'x_7': 10000, 'x_2': 1000, 'x_8': 400, 'x_27': 9100, 'x_1': 450, 'x_9': 0, 'x_17': 30, 'x_22': 2800, 'x_6': 100, 'x_3': 6840, 'x_16': 0}. Best is trial 0 with value: 2.2193561511084323.

Best trial: 0. Best value: 2.21936:   0%|          | 2/1000 [00:21<2:51:30, 10.31s/it, 21.47/300 seconds]

[I 2025-10-17 16:16:47,241] Trial 1 finished with value: 2.2193561511084323 and parameters: {'x_27': 9100, 'x_8': 510, 'x_9': 277, 'x_12': 20012, 'x_19': 700, 'x_2': 1002, 'x_13': 60, 'x_5': 24004, 'x_20': 273, 'x_0': 159, 'x_23': 10, 'x_7': 10001, 'x_14': 50, 'x_25': 35, 'x_15': 1314, 'x_1': 450, 'x_4': 11040, 'x_21': 4, 'x_3': 6846, 'x_24': 10000, 'x_18': 29, 'x_26': 402, 'x_11': 38, 'x_16': 4, 'x_10': 18519, 'x_22': 2800, 'x_17': 30, 'x_6': 104}. Best is trial 0 with value: 2.2193561511084323.

Best trial: 0. Best value: 2.21936:   0%|          | 3/1000 [00:30<2:38:01,  9.51s/it, 30.02/300 seconds]

[I 2025-10-17 16:16:55,794] Trial 2 finished with value: 2.136835190537566 and parameters: {'x_9': 146242, 'x_4': 881, 'x_11': 332, 'x_24': 20, 'x_18': 0, 'x_10': 18500, 'x_13': 60, 'x_15': 1250, 'x_22': 2800, 'x_23': 0, 'x_7': 10000, 'x_16': 0, 'x_2': 1000, 'x_21': 0, 'x_8': 400, 'x_26': 400, 'x_5': 24000, 'x_6': 100, 'x_1': 450, 'x_25': 0, 'x_17': 30, 'x_20': 270, 'x_0': 150, 'x_12': 0, 'x_27': 0, 'x_14': 0, 'x_3': 0, 'x_19': 0}. Best is trial 0 with value: 2.2193561511084323.

Best trial: 0. Best value: 2.21936:   0%|          | 4/1000 [00:38<2:28:13,  8.93s/it, 38.06/300 seconds]

[I 2025-10-17 16:17:03,831] Trial 3 finished with value: 2.136835190537566 and parameters: {'x_16': 9638, 'x_2': 1266, 'x_27': 9731, 'x_11': 68377, 'x_20': 327, 'x_14': 0, 'x_6': 100, 'x_7': 10000, 'x_25': 0, 'x_24': 0, 'x_15': 1250, 'x_23': 0, 'x_22': 2800, 'x_17': 30, 'x_10': 18500, 'x_26': 400, 'x_1': 450, 'x_19': 0, 'x_12': 0, 'x_5': 24000, 'x_18': 0, 'x_13': 60, 'x_4': 0, 'x_9': 0, 'x_8': 400, 'x_3': 0, 'x_21': 0, 'x_0': 150}. Best is trial 0 with value: 2.2193561511084323.

Best trial: 0. Best value: 2.21936:   0%|          | 5/1000 [00:46<2:27:48,  8.91s/it, 46.95/300 seconds]

[I 2025-10-17 16:17:12,719] Trial 4 finished with value: 2.1627388731811945 and parameters: {'x_9': 70355, 'x_22': 47, 'x_5': 223, 'x_11': 35203, 'x_8': 38325, 'x_26': 400, 'x_18': 0, 'x_16': 0, 'x_4': 0, 'x_25': 0, 'x_21': 0, 'x_13': 60, 'x_0': 150, 'x_10': 18500, 'x_7': 10000, 'x_14': 0, 'x_20': 270, 'x_6': 100, 'x_24': 0, 'x_19': 0, 'x_3': 0, 'x_12': 0, 'x_2': 1000, 'x_1': 0, 'x_15': 0, 'x_23': 0, 'x_27': 0, 'x_17': 0}. Best is trial 0 with value: 2.2193561511084323.

Best trial: 0. Best value: 2.21936:   1%|          | 6/1000 [00:55<2:24:43,  8.74s/it, 55.34/300 seconds]

[I 2025-10-17 16:17:21,108] Trial 5 finished with value: 2.1627388731811945 and parameters: {'x_14': 89, 'x_24': 10990, 'x_20': 4002, 'x_13': 692, 'x_27': 5631, 'x_7': 67663, 'x_0': 405, 'x_6': 107, 'x_26': 400, 'x_18': 0, 'x_10': 18500, 'x_8': 38000, 'x_2': 1000, 'x_9': 0, 'x_11': 0, 'x_21': 0, 'x_25': 0, 'x_5': 0, 'x_3': 0, 'x_19': 0, 'x_16': 0, 'x_12': 0, 'x_15': 0, 'x_1': 0, 'x_4': 0, 'x_23': 0, 'x_17': 0, 'x_22': 0}. Best is trial 0 with value: 2.2193561511084323.

Best trial: 0. Best value: 2.21936:   1%|          | 7/1000 [01:03<2:21:38,  8.56s/it, 63.53/300 seconds]

[I 2025-10-17 16:17:29,303] Trial 6 finished with value: 2.137840445666359 and parameters: {'x_18': 3449, 'x_27': 5744, 'x_11': 137833, 'x_8': 2, 'x_16': 271, 'x_7': 66000, 'x_15': 0, 'x_24': 10000, 'x_0': 150, 'x_17': 0, 'x_19': 0, 'x_1': 0, 'x_14': 50, 'x_20': 1280, 'x_26': 400, 'x_23': 0, 'x_9': 0, 'x_22': 0, 'x_4': 0, 'x_6': 100, 'x_5': 0, 'x_21': 0, 'x_12': 0, 'x_25': 0, 'x_2': 0, 'x_10': 0, 'x_3': 0, 'x_13': 0}. Best is trial 0 with value: 2.2193561511084323.

Best trial: 0. Best value: 2.21936:   1%|          | 8/1000 [01:11<2:20:48,  8.52s/it, 71.96/300 seconds]

[I 2025-10-17 16:17:37,728] Trial 7 finished with value: 2.147890033934447 and parameters: {'x_3': 21684, 'x_5': 13995, 'x_8': 14202, 'x_11': 7083, 'x_16': 3056, 'x_20': 2616, 'x_27': 2827, 'x_17': 703, 'x_6': 610, 'x_0': 1071, 'x_1': 634, 'x_26': 2462, 'x_24': 10134, 'x_22': 342, 'x_4': 9, 'x_19': 1, 'x_2': 0, 'x_7': 66000, 'x_13': 0, 'x_21': 0, 'x_14': 50, 'x_25': 0, 'x_9': 0, 'x_18': 0, 'x_23': 0, 'x_12': 0, 'x_10': 0, 'x_15': 0}. Best is trial 0 with value: 2.2193561511084323.

Best trial: 8. Best value: 2.26279:   1%|          | 9/1000 [01:15<1:53:08,  6.85s/it, 75.14/300 seconds]

[I 2025-10-17 16:17:40,914] Trial 8 finished with value: 2.2627863407020565 and parameters: {'x_4': 46626, 'x_26': 400, 'x_27': 0, 'x_20': 1280, 'x_16': 0, 'x_21': 0, 'x_6': 100, 'x_10': 0, 'x_24': 10000, 'x_2': 0, 'x_22': 0, 'x_1': 183, 'x_17': 20, 'x_18': 0, 'x_8': 15507, 'x_25': 0, 'x_13': 0, 'x_12': 0, 'x_7': 66000, 'x_14': 50, 'x_19': 0, 'x_15': 0, 'x_11': 0, 'x_5': 0, 'x_9': 0, 'x_3': 5529, 'x_0': 0, 'x_23': 0}. Best is trial 8 with value: 2.2627863407020565.

Best trial: 8. Best value: 2.26279:   1%|          | 10/1000 [01:15<1:19:39,  4.83s/it, 75.44/300 seconds]

[I 2025-10-17 16:17:41,215] Trial 9 finished with value: 2.2627863407020565 and parameters: {'x_14': 50, 'x_25': 18546, 'x_3': 3577, 'x_26': 0, 'x_23': 3, 'x_18': 2, 'x_20': 0, 'x_22': 0, 'x_21': 1, 'x_27': 0, 'x_17': 0, 'x_1': 0, 'x_8': 15200, 'x_9': 0, 'x_12': 0, 'x_13': 0, 'x_0': 0, 'x_19': 0, 'x_6': 100, 'x_7': 66000, 'x_2': 0, 'x_10': 0, 'x_16': 0, 'x_11': 0, 'x_4': 44000, 'x_15': 0, 'x_24': 0, 'x_5': 0}. Best is trial 8 with value: 2.2627863407020565.

Best trial: 8. Best value: 2.26279:   1%|          | 11/1000 [01:16<1:01:28,  3.73s/it, 76.68/300 seconds]

[I 2025-10-17 16:17:42,451] Trial 10 finished with value: 2.2230905345591534 and parameters: {'x_24': 6803, 'x_2': 334, 'x_3': 10028, 'x_19': 249, 'x_25': 118864, 'x_10': 0, 'x_15': 0, 'x_0': 0, 'x_20': 0, 'x_17': 0, 'x_26': 0, 'x_9': 0, 'x_1': 0, 'x_13': 0, 'x_23': 0, 'x_12': 0, 'x_6': 100, 'x_7': 66000, 'x_16': 0, 'x_27': 0, 'x_18': 0, 'x_4': 44000, 'x_11': 0, 'x_5': 0, 'x_22': 0, 'x_14': 0, 'x_21': 0, 'x_8': 0}. Best is trial 8 with value: 2.2627863407020565.

Best trial: 8. Best value: 2.26279:   1%|          | 12/1000 [01:17<48:00,  2.92s/it, 77.74/300 seconds]

[I 2025-10-17 16:17:43,506] Trial 11 finished with value: 2.2245684738703058 and parameters: {'x_21': 326, 'x_14': 36, 'x_3': 7101, 'x_18': 1059, 'x_25': 12735, 'x_23': 97, 'x_27': 2322, 'x_26': 2, 'x_20': 933, 'x_16': 148, 'x_15': 360, 'x_10': 3279, 'x_2': 278, 'x_24': 2662, 'x_11': 1742, 'x_1': 133, 'x_9': 1336, 'x_17': 11, 'x_5': 796, 'x_6': 100, 'x_0': 0, 'x_8': 2008, 'x_22': 4, 'x_12': 4, 'x_13': 2, 'x_7': 66002, 'x_4': 44003, 'x_19': 0}. Best is trial 8 with value: 2.2627863407020565.

Best trial: 8. Best value: 2.26279:   1%|▏         | 13/1000 [01:19<42:35,  2.59s/it, 79.58/300 seconds]

[I 2025-10-17 16:17:45,342] Trial 12 finished with value: 2.260449701964125 and parameters: {'x_19': 204, 'x_5': 6169, 'x_16': 139, 'x_6': 69, 'x_27': 0, 'x_11': 0, 'x_25': 0, 'x_4': 44000, 'x_8': 18970, 'x_23': 0, 'x_13': 0, 'x_26': 0, 'x_24': 0, 'x_0': 0, 'x_3': 6840, 'x_22': 0, 'x_2': 0, 'x_9': 0, 'x_17': 0, 'x_18': 0, 'x_1': 0, 'x_15': 0, 'x_10': 0, 'x_7': 0, 'x_20': 0, 'x_12': 0, 'x_21': 0, 'x_14': 0}. Best is trial 8 with value: 2.2627863407020565.

Best trial: 8. Best value: 2.26279:   1%|▏         | 14/1000 [01:20<1:34:09,  5.73s/it, 80.21/300 seconds]

[I 2025-10-17 16:17:45,974] Trial 13 finished with value: 2.260449701964125 and parameters: {'x_15': 333, 'x_10': 5917, 'x_13': 27, 'x_7': 48917, 'x_14': 38, 'x_9': 6087, 'x_3': 7882, 'x_24': 6756, 'x_5': 2179, 'x_26': 114, 'x_1': 132, 'x_12': 1722, 'x_4': 47553, 'x_23': 296, 'x_2': 161, 'x_8': 18888, 'x_17': 18, 'x_19': 117, 'x_25': 337, 'x_27': 2, 'x_22': 1, 'x_20': 1, 'x_6': 0, 'x_11': 0, 'x_18': 1, 'x_21': 0, 'x_16': 0, 'x_0': 0}. Best is trial 8 with value: 2.2627863407020565.

Convert to services dataframe

In [11]:
solution_df = facade.solution_to_services_df(best_x)
solution_df

     block_id   service_type  site_area  build_floor_area  capacity  count
6        3442           bank        0.0             400.0       250      1
10       3442         cinema        0.0             700.0       450      1
12       3442   kindergarten     3520.0             240.0        80      1
16       3442   kindergarten        0.0             320.0       180      1
21       3442         market    11000.0           25000.0     15000      4
27       3442           cafe      100.0              75.0        25      1
37       3442  swimming_pool     6000.0            3500.0       500      1
38       3442  swimming_pool    10000.0            5500.0      1000      6
39       3442       dog_park      400.0               0.0       106     38
44       3442           post        0.0             320.0       100     86
61       3442            bar        0.0              40.0        30      1
64       3442     playground       50.0               0.0        20      1
82       3442    convenience        0.0              25.0        50      1
110      3442    hairdresser        0.0              50.0        10      1
118      3442       pharmacy        0.0              40.0        60      1

Extract area dataframe from solution

In [ ]:
blocks_gdf['block_id'] = blocks_gdf.index
blocks_gdf.to_file

In [ ]:
solution_area_df = facade.get_solution_area_df(best_x)
solution_area_df.to_csv(f'solution_area.csv')
solution_area_df.loc[blocks_lu.keys()]

In [ ]:
solution_area_df.population.sum()

### Visualization

In [ ]:
import matplotlib.pyplot as plt


def plot_df(df):
    df_called_obj = df.loc[df["called_obj"] == True]

    plt.scatter(df_called_obj["func_evals"], df_called_obj["best_val"], c="red", s=5)

    df_called_obj = pd.concat(
        [pd.DataFrame([[-1, None, 0, 0, None, 0, False, 0]], columns=df_called_obj.columns), df_called_obj]
    )
    plt.plot(
        df_called_obj["func_evals"], df_called_obj["best_val"], label="Best Value (TPE)", color="blue", linewidth=1
    )
    # Добавление точек с цветом в зависимости от 'called_obj'
    # Настройка осей и заголовка
    plt.xlabel("Number of objective evaluation")
    plt.ylabel("Best Value")
    plt.title("Best Value Across Trials")
    plt.legend()
    plt.grid(True)

    # Отображение графика
    plt.show()

In [ ]:
tpe_df

In [ ]:
tpe_df

In [ ]:
import pandas as pd

tpe_df = pd.read_csv("C:/itmo/MASTER_PLAN/blocksnet/examples/synthesis/services_planning/provisions.csv")
plot_df(tpe_df)

In [ ]:
facade.save_delta_demand(best_x)
population_df = pd.read_csv("demand_services.csv")
population_df.head(20)